import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { NavLinks } from '@/components/nav-links';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

// `app/layout.js` 是根布局，是必需的，必须包含 html 和 body 标签。所有路由下的内容都渲染到`children`所在位置
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased root-layout`}
      >
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
